spring:
  rabbitmq:
    host: 47.112.240.235
    password: guest
    username: guest
    listener:
      type: simple
      simple:
        default-requeue-rejected: false
        acknowledge-mode: manual
    port: 8085
    publisher-returns: true #表示开启生产者确认模式
    publisher-confirm-type: correlated
#  spring.rabbitmq.listener.simple.retry.max-attempts=5  最大重试次数
#  spring.rabbitmq.listener.simple.retry.enabled=true 是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
#  spring.rabbitmq.listener.simple.retry.initial-interval=5000 重试间隔时间（单位毫秒）
#  spring.rabbitmq.listener.simple.default-requeue-rejected=false 重试次数超过上面的设置之后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列）